
version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
    ports:
      - '7881:80'
      - '7883:443'
      - '7882:22'
    volumes:
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/data:/var/opt/gitlab
      - /home/gitlab/logs:/var/log/gitlab
    privileged: true