version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.391
    container_name: jenkins
    hostname: jenkins
    ports:
      - "8077:8080"
      - "5007:50000"
    volumes:
      - /home/jenkins:/var/jenkins_home
      - /home/:/home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker #宿主机的docker可执行映射到镜像里面 后面build的时候会用到
    privileged: true